CREATE TABLE IF NOT EXISTS athletes(
    id INTEGER,
    name TEXT NOT NULL UNIQUE,
    attack INTEGER NOT NULL CHECK(attack BETWEEN 1 AND 20),
    defense INTEGER NOT NULL CHECK(defense BETWEEN 1 AND 20),
    serve INTEGER NOT NULL CHECK(serve BETWEEN 1 AND 20),
    PRIMARY KEY(id)
);
